apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: globaldvash-com-tls
spec:
  secretName: globaldvash-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: globaldvash.com
  dnsNames:
    - globaldvash.com
    - www.globaldvash.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - globaldvash.com
          - www.globaldvash.com
